"""
Django settings for rod project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV = os.getenv("ENV", "development")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-dev-key")
API_KEY = os.getenv("API_KEY", "dev-api-key")
PATREON_WEBHOOK_SECRET = os.getenv("PATREON_WEBHOOK_SECRET", "")

# Discord constants
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN", "")
DISCORD_DEBUG_CHANNEL = os.getenv("DISCORD_DEBUG_CHANNEL", "")
# Toggle to enable/disable sending logs to Discord (e.g., set to 'false' to disable)
DISCORD_LOGGING_ENABLED = os.getenv(
    "DISCORD_LOGGING_ENABLED", "true"
).strip().lower() in {"1", "true", "yes", "on"}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("ENV", "development") == "development"


# Conditional settings based on ENV
if ENV == "development":
    # Development environment
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    SECURE_SSL_REDIRECT = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSRF_TRUSTED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]
else:
    # Production & preproduction environment
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "[::1]",
    ]

    if ENV == "preproduction":
        ALLOWED_HOSTS.append("dev.realmofdarkness.app")
    else:
        ALLOWED_HOSTS.extend(
            [
                "realmofdarkness.app",
                "www.realmofdarkness.app",
            ]
        )

    SECURE_SSL_REDIRECT = False  # handled by nginx
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True


# Application definition

# Common apps for both development and production
COMMON_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "discordauth.apps.DiscordauthConfig",
    "main.apps.MainConfig",
    "haven.apps.HavenConfig",
    "chronicle.apps.ChronicleConfig",
    "bot.apps.BotConfig",
    "patreon.apps.PatreonConfig",
    "channels",
    "rest_framework",
]

if DEBUG:
    # Development mode apps
    INSTALLED_APPS = ["daphne"] + COMMON_APPS
else:
    # Production mode apps
    INSTALLED_APPS = COMMON_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "rod.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "../frontend/build/"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rod.wsgi.application"
# Channels
ASGI_APPLICATION = "rod.asgi.application"

# Get Redis configuration
REDIS_DB_INDEX = os.getenv("REDIS_DB_INDEX", "0")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"redis://127.0.0.1:6379/{REDIS_DB_INDEX}"],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://127.0.0.1:6379/{REDIS_DB_INDEX}",
    }
}


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite3")
DB_NAME = os.getenv("DB_NAME", "db.sqlite3")

if DB_ENGINE == "sqlite3":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / DB_NAME,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME", "realm_of_darkness"),
            "USER": os.getenv("DB_USER", ""),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", ""),
            "OPTIONS": {"sql_mode": "traditional", "charset": "utf8mb4"},
            "CONN_MAX_AGE": 29,
        }
    }

    # Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        # Other authentication classes...
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "50/day",  # Anonymous users - restricted
        "standard_user": "2000/day",  # Regular authenticated users
        "supporter_user": "5000/day",  # Supporters (tier 1-2)
        "premium_user": "10000/day",  # Premium supporters (tier 3+)
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Custom Auth Backend
# https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#specifying-authentication-backends

AUTHENTICATION_BACKENDS = ["discordauth.backends.DiscordAuthBackend"]

# Custom User Model
# https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#extending-the-existing-user-model

AUTH_USER_MODEL = "discordauth.User"

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "../frontend/build/static/",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging configuration with Discord handler and fallbacks
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "%(levelname)s | %(name)s | %(message)s",
        },
        "verbose": {
            "format": "%(asctime)s | %(levelname)s | %(name)s | %(pathname)s:%(lineno)d | %(message)s",
        },
    },
    "filters": {
        # Allow our app loggers, and ERROR+ from any other logger
        "discord_allow": {"()": "rod.logging_handlers.get_discord_allow_filter"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "simple",
        },
        "file_root": {
            "class": "logging.FileHandler",
            "level": "WARNING",
            "filename": str(BASE_DIR / "root.log"),
            "encoding": "utf-8",
            "formatter": "verbose",
        },
        "file_django": {
            "class": "logging.FileHandler",
            "level": "WARNING",
            "filename": str(BASE_DIR / "django.log"),
            "encoding": "utf-8",
            "formatter": "verbose",
        },
        "file_debug": {
            "class": "logging.FileHandler",
            "level": "DEBUG",
            "filename": str(BASE_DIR / "debug.log"),
            "encoding": "utf-8",
            "formatter": "simple",
        },
        "discord": {
            # Use callable style so we can read settings at runtime
            "()": "rod.logging_handlers.get_discord_embed_handler",
            "level": "INFO",  # INFO+ to Discord by default
            "filters": ["discord_allow"],
        },
    },
    "root": {
        # DEBUG: console + discord (optional), no files
        # PROD: file + discord (optional), no console
        "handlers": (
            (["console"] if DEBUG else [])
            + (["discord"] if DISCORD_LOGGING_ENABLED else [])
            + ([] if DEBUG else ["file_root"])
        ),
        "level": "DEBUG" if DEBUG else "WARNING",
    },
    "loggers": {
        "django": {
            # Avoid spamming Discord with framework noise; filter limits to ERROR unless it's our app
            "handlers": (
                ([] if DEBUG else ["file_django"])
                + (["console"] if DEBUG else [])
                + (["discord"] if DISCORD_LOGGING_ENABLED else [])
            ),
            "level": "WARNING",
            "propagate": False,
        },
        "django.server": {
            "handlers": (["console"] if DEBUG else []),
            "propagate": False,
        },
        # Legacy custom logger name preserved
        "DEBUG": {
            "handlers": (
                ([] if DEBUG else ["file_debug"])
                + (["console"] if DEBUG else [])
                + (["discord"] if DISCORD_LOGGING_ENABLED else [])
            ),
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
